version: 0.1

phases:
  install:
    commands:
      - echo $SHELL
      - printenv
      - chmod 700 $CODEBUILD_SRC_DIR/build_and_deploy.sh
      - cd $CODEBUILD_SRC_DIR/
      - ./build_and_deploy.sh
